### PR TITLE
Fix link in card 'Are you a package author'

### LINKED ISSUE #137: Incorrect link in "Are you a package author / maintainer?" card on index.md?
Again I know this is all under construction but I think the link in this card:

https://github.com/pyOpenSci/contributing-guide/blob/b7e7d80d6eeb582fcb4f346a2d8421f70ff507df/index.md?plain=1#L58

```
:::{grid-item-card}
:link: software-peer-review-guide/reviewer-guide

:link-type: doc
:class-header: bg-light

Are you a package author / maintainer? ✨
^^^

Learn how to submit a package for peer review with pyOpenSci.
:::
```

should instead be
```
:link: software-peer-review-guide/author-guide
```

Happy to fix with a PR if so

### PR DESCRIPTION
**Pull request by NickleDave**
fixes #137

### CODE REVIEW

**Comment by NickleDave** [comment]
🤔 I looked at the artifact on CircleCI but it doesn't appear the link works.  
Not clear to me if any of them are working?  
Also not sure how to troubleshoot, will probably try building locally

**Comment by lwasser** [comment]
i can look at it! i'm close to getting website pr's cleaned up.

**Comment by lwasser** [comment]
So the links were actually broken - circle ci is ok in this pr #142 i'm pretty sure. i'll merge that one and we can see if this PR is still needed. there were a handful of issues with the landing page syntax that I needed to fix to make it render properly.

**Comment by lwasser** [comment]
@NickleDave thank you so much for this PR. i think i was able to fix it in the larger PR that i submitted -- the cards had a lot of issues. please look here. https://www.pyopensci.org/peer-review-guide/ and if you still see issues we can totally reopen this PR. i think i had found some format issues with the cards as well that needed to be fixed in addition to the link issue that you caught!!

**Pull request closed without merging**
